"// dummy pspkernel.h"  
"typedef int SceUID;"  
"int sceKernelCreateMutex(const char*, int, int, void*);"  
"void sceKernelDeleteMutex(SceUID);"  
"int sceKernelMutexLock(SceUID, int, void*);"  
"int sceKernelMutexUnlock(SceUID);"  
"int sceAudioChReserve(int, int, int);"  
"void sceAudioChRelease(int);"  
"void sceAudioOutputPannedBlocking(int, int, int, short*);"  
"#define PSP_AUDIO_FORMAT_STEREO 0"  
"#define pspDebugScreenPrintf printf"  
