"""Generate native 16x16 RGBA analog hints used by the button prompt renderer."""
import argparse
import re
from pathlib import Path

NAMES = ('btn_analog','btn_analog_up','btn_analog_dn','btn_analog_lf','btn_analog_rt')

def sample(x, y, direction):
    if direction == 'down': x,y=15-x,15-y
    elif direction == 'left': x,y=15-y,x
    elif direction == 'right': x,y=y,15-x
    radius=(x-7.5)**2+(y-7.5)**2
    if radius>6.8**2: return None
    color=190 if radius>5.8**2 else 45
    if radius<3.8**2: color=105 if int(x+y)%2 else 85
    if direction and ((3<=y<=8 and abs(x-7.5)<=(y-3)*0.65) or
                      (7<=y<=11 and abs(x-7.5)<=0.9)):
        color=240
    return (color,color,color)

def pixels(direction):
    result=[]
    for y in range(16):
        for x in range(16):
            covered=[value for sy in range(4) for sx in range(4)
                     if (value:=sample(x+(sx+0.5)/4,y+(sy+0.5)/4,direction)) is not None]
            if covered:
                result.extend([round(sum(c[i] for c in covered)/len(covered)) for i in range(3)]+[round(255*len(covered)/16)])
            else:
                result.extend((0,0,0,0))
    return bytes(result)

def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write',action='store_true')
    parser.add_argument('--preview',type=Path)
    args=parser.parse_args()
    header=Path(__file__).resolve().parents[1]/'src/btn_icons.h'
    with header.open(encoding='utf-8',newline='') as stream:
        text=stream.read()
    newline='\r\n' if '\r\n' in text else '\n'
    originals={}
    generated={name:pixels(direction) for name,direction in
               zip(NAMES,(None,'up','down','left','right'))}
    for name,data in generated.items():
        pattern=rf'(static const unsigned char __attribute__\(\(aligned\(64\)\)\) {name}\[1024\] = \{{)(.*?)(\n\}};)'
        match=re.search(pattern,text,re.S)
        if not match: raise RuntimeError(f'Array {name} missing')
        originals[name]=bytes(int(value,16) for value in re.findall(r'0x([0-9a-fA-F]{2})u',match[2]))
        if len(originals[name])!=1024: raise RuntimeError(f'Wrong size: {name}')
        if args.write:
            if any(originals[name]) and originals[name]!=data:
                raise RuntimeError(f'Refusing to replace unexpected nonblank artwork: {name}')
            body=newline+''.join('    '+','.join(f'0x{value:02X}u' for value in data[row:row+64])+','+newline for row in range(0,1024,64))
            text=text[:match.start(2)]+body.rstrip('\r\n')+text[match.end(2):]
        elif originals[name]!=data:
            raise RuntimeError(f'{name} does not match generated visible artwork')
        assert len(data)==1024 and sum(data[3::4])>0
    assert len(set(generated.values()))==5
    if args.write:
        with header.open('w',encoding='utf-8',newline='') as stream:
            stream.write(text)
    if args.preview:
        from PIL import Image
        preview=Image.new('RGB',(5*80,80),(24,24,24))
        for index,data in enumerate(generated.values()):
            image=Image.frombytes('RGBA',(16,16),data).resize((64,64),Image.Resampling.NEAREST)
            preview.paste(image,(index*80+8,8),image)
        args.preview.parent.mkdir(parents=True,exist_ok=True)
        preview.save(args.preview)
    print('PASS five distinct visible 16x16 RGBA analog badges, aligned arrays, exact generated bytes.')

if __name__=='__main__': main()
